name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Determine Version
      run: echo "NXIQ_VERSION=$(grep release Dockerfile  | cut -d "=" -f2 | tr -d '" \')" >> $GITHUB_ENV
      
    - run: echo "Building NXIQ ${{ env.NXIQ_VERSION }} for ARM"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64,linux/amd64
        push: true
        tags: madpah/nexus-iq-server:latest , madpah/nexus-iq-server:${{ env.NXIQ_VERSION }}
        
    - name: Build and push (SLIM)
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.slim
        platforms: linux/arm64,linux/amd64
        push: true
        tags: madpah/nexus-iq-server:latest-slim , madpah/nexus-iq-server:${{ env.NXIQ_VERSION }}-slim
